connections:
  dbType: postgres
  dbHost: postgresql
  dbPort: 5432
  dbName: onlyoffice
  dbUser: postgres
  redisHost: redis-master
  redisPort: 6379
  amqpUri: amqp://user:password@rabbitmq
  amqpType: rabbitmq

persistence:
  storageClass: "nfs"
  size: 8Gi

example:
  enabled: true

documentserver:
  replicas: 2
  livenessProbeEnabled: true
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /index.html
      port: 80
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 3
  startupProbeEnabled: true
  startupProbe:
    httpGet:
      path: /index.html
      port: 80
    failureThreshold: 30
    periodSeconds: 60
  ContainerImage: onlyoffice/documentserver-de:6.4.2.6
  resources:
    ##Example:
    ##requests:
    ##  memory: "256Mi"
    ##  cpu: "100m"
    requests: {}
    ##limits:
    ##  memory: "2Gi"
    ##  cpu: "1000m"
    limits: {}

jwt:
  enabled: true
  secret: MYSECRET

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ssl:
    enabled: false
    host: example.com
    secret: tls

rejectUnauthorizedTls:
  enabled: false
