{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: onlyoffice
  annotations:
  {{ if .Values.ingress.annotations }}
    {{ .Values.ingress.annotations }}
  {{ end }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  {{ if .Values.ingress.ssl.enabled }}
  tls: 
  - hosts:
    - {{ .Values.ingress.ssl.host }}
    secretName: {{ .Values.ingress.ssl.secret }}
  {{ end }}
  rules:
  {{ if .Values.ingress.ssl.enabled }}
  - host: {{ .Values.ingress.ssl.host }}
  {{ else }}
  - host:
  {{ end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: onlyoffice
          servicePort: 80
{{ end }}
