apiVersion: v1
kind: ConfigMap
metadata:
  name: onlyoffice-env
data:
  DB_TYPE: {{ .Values.connections.dbType }}
  DB_HOST: {{ .Values.connections.dbHost }}
  DB_PORT: {{ .Values.connections.dbPort | quote}}
  DB_NAME: {{ .Values.connections.dbName }}
  DB_USER: {{ .Values.connections.dbUser }}
  REDIS_SERVER_HOST: {{ .Values.connections.redisHost }}
  REDIS_SERVER_PORT: {{ .Values.connections.redisPort | quote}}
  AMQP_TYPE: {{ .Values.connections.amqpType }}
  AMQP_URI: {{ .Values.connections.amqpUri }}
  USE_UNAUTHORIZED_STORAGE: {{ .Values.rejectUnauthorizedTls.enabled }}
